"""Editable defaults for RepoTrim's rule-based MVP."""

from __future__ import annotations

IGNORED_FILE_PATTERNS = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.ico",
    "*.svg",
    "*.pdf",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.mp4",
    "*.mov",
    "*.mp3",
    "*.wav",
    ".env",
    ".env.local",
    ".env.production",
}

SUPPORTED_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".cs",
    ".java",
    ".cpp",
    ".c",
    ".h",
    ".hpp",
    ".go",
    ".rs",
    ".rb",
    ".php",
    ".html",
    ".css",
    ".scss",
    ".json",
    ".yaml",
    ".yml",
    ".md",
    ".sql",
    ".txt",
    ".toml",
    ".ini",
    ".cfg",
    ".vue",
    ".svelte",
    ".kt",
    ".kts",
    ".swift",
    ".dart",
    ".sh",
    ".bash",
    ".zsh",
    ".ps1",
    ".xml",
    ".gradle",
    ".properties",
    ".proto",
    ".graphql",
    ".gql",
    ".prisma",
    ".csproj",
}

LANGUAGE_BY_EXTENSION = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".cs": "csharp",
    ".java": "java",
    ".cpp": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".md": "markdown",
    ".sql": "sql",
    ".txt": "text",
    ".toml": "toml",
    ".ini": "text",
    ".cfg": "text",
    ".vue": "vue",
    ".svelte": "svelte",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".dart": "dart",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".ps1": "powershell",
    ".xml": "xml",
    ".gradle": "gradle",
    ".properties": "text",
    ".proto": "protobuf",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".prisma": "prisma",
    ".csproj": "xml",
}

STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "in",
    "is",
    "it",
    "not",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
    "fix",
    "add",
    "change",
    "make",
    "work",
}

KEYWORD_VARIANTS = {
    "update": {"update", "updated", "updating"},
    "save": {"save", "saved", "saving"},
    "saving": {"save", "saved", "saving"},
    "auth": {"auth", "authentication"},
    "authentication": {"auth", "authentication"},
    "login": {"login", "signin", "sign", "signing"},
    "signin": {"login", "signin"},
    "employee": {"employee", "employees"},
    "employees": {"employee", "employees"},
    "invoice": {"invoice", "invoices"},
    "invoices": {"invoice", "invoices"},
    "payment": {"payment", "payments"},
    "payments": {"payment", "payments"},
    "user": {"user", "users"},
    "users": {"user", "users"},
    "rbac": {"rbac", "role", "roles", "permission", "permissions", "authorization", "authorize", "access", "policy", "policies", "guard", "guards"},
    "access": {"access", "authorization", "authorize", "permission", "permissions", "role", "roles", "guard", "guards", "policy", "policies"},
    "accessing": {"access", "authorization", "authorize", "permission", "permissions", "role", "roles", "guard", "guards", "policy", "policies"},
    "role": {"role", "roles", "rbac", "permission", "permissions"},
    "roles": {"role", "roles", "rbac", "permission", "permissions"},
    "permission": {"permission", "permissions", "authorize", "authorization", "rbac"},
    "permissions": {"permission", "permissions", "authorize", "authorization", "rbac"},
    "tool": {"tool", "tools"},
    "tools": {"tool", "tools"},
}

SUPPORTED_FILENAMES = {
    "dockerfile",
    "makefile",
    "procfile",
    "gemfile",
    "rakefile",
    "jenkinsfile",
    ".env.example",
}

LOG_IMPORTANT_PATTERNS = (
    "error",
    "exception",
    "failed",
    "failure",
    "cannot",
    "can't",
    "undefined",
    "not defined",
    "not found",
    "does not exist",
    "invalid",
    "denied",
    "timeout",
    "traceback",
    "stack trace",
    "fatal",
    "panic",
    "segmentation fault",
    "npm err",
    "typeerror",
    "referenceerror",
    "syntaxerror",
    "nullreferenceexception",
    "invalidoperationexception",
    "sqlexception",
    "dbupdateexception",
    "foreign key",
    "constraint",
    "404",
    "400",
    "401",
    "403",
    "500",
)

MAX_FILE_SIZE_BYTES = 500 * 1024
MAX_RANKED_FILES = 8
SNIPPET_LINE_WINDOW = 15
SMALL_FILE_TOKEN_LIMIT = 1200
MAX_SNIPPET_TOKENS_PER_FILE = 3000
MAX_CONTEXT_PACKET_TOKENS = 18000
